# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('value', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=500)),
                ('Answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizName', models.CharField(max_length=250)),
                ('QuizDate', models.DateTimeField(auto_now_add=True)),
                ('QuizDescription', models.CharField(max_length=1500)),
                ('Author', models.CharField(max_length=250)),
                ('mcqaval', models.IntegerField()),
                ('pcqaval', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displayquizes.quiz'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='Quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displayquizes.quiz'),
        ),
    ]
