# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayquizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='mcqaval',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pcqaval',
            field=models.IntegerField(default=4),
        ),
    ]
