# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayquizes', '0002_auto_20170106_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
