# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displayquizes', '0003_auto_20170106_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='qtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displayquizes.qtype'),
        ),
    ]
